### ISSUE TITLE
Check compatibility for new EOS releases

### ISSUE THREAD

**Issue by mreboud** [eos/data#1]
The idea would be to run the analyses, maybe in a light version, to ensure backward compatibility, or at least be aware of any issue.

**Comment by dvandyk** [comment]
In light of that, a new issue has been added to create an ``eos-analysis validate`` task (eos/eos#860).

Once available, a workflow should periodically (ideally a few hours after the weekly build)
- [x] iterate over all branches withes names that match ``YYYY-MM-XY``
- [x] run ``eos-analysis validate`` on its analysis file
- [ ] ~if the validation fails: open an issue in the eos/data repository.~ Not a good idea, since we do not want to open issue repeatedly when the new workflow runs on a schedule

**Comment by dvandyk** [comment]
Resolved by #2.
